export const COMMON_DRUGS = [
  { name: "Aspirin", smiles: "CC(=O)OC1=CC=CC=C1C(=O)O", desc: "Anti-inflammatory & blood thinner" },
  { name: "Acetaminophen (Paracetamol)", smiles: "CC(=O)NC1=CC=C(C=C1)O", desc: "Pain reliever & fever reducer" },
  { name: "Ibuprofen", smiles: "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O", desc: "Nonsteroidal anti-inflammatory drug (NSAID)" },
  { name: "Caffeine", smiles: "CN1C=NC2=C1C(=O)N(C(=O)N2C)C", desc: "Central nervous system stimulant" },
  { name: "Warfarin", smiles: "CC(=O)CC(C1=CC=CC=C1)C1=C(O)C2=CC=CC=C2OC1=O", desc: "Anticoagulant (blood thinner)" },
  { name: "Metformin", smiles: "CN(C)C(=N)NC(=N)N", desc: "First-line medication for type 2 diabetes" },
  { name: "Atorvastatin", smiles: "CC(C)C1=C(C(=O)NC2=CC=CC=C2)C(=C(N1CC[C@@H](O)C[C@@H](O)CC(O)=O)C1=CC=C(F)C=C1)C1=CC=CC=C1", desc: "Statin medication to lower cholesterol" },
  { name: "Lisinopril", smiles: "N[C@@H](CCCC)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCC1=CC=CC=C1)C(=O)O", desc: "ACE inhibitor for high blood pressure" },
  { name: "Albuterol", smiles: "CC(C)(C)NCC(O)C1=CC(CO)=C(O)C=C1", desc: "Bronchodilator for asthma" },
  { name: "Diazepam (Valium)", smiles: "CN1C(=O)CN=C(C2=CC=CC=C2)C3=C1C=CC(Cl)=C3", desc: "Benzodiazepine for anxiety & seizures" },
  { name: "Penicillin V", smiles: "CC1(C(N2C(S1)C(C2=O)NC(=O)COC3=CC=CC=C3)C(=O)O)C", desc: "Beta-lactam antibiotic" },
  { name: "Omeprazole (Prilosec)", smiles: "CC1=C(C(=C(N=C1CS(=O)C2=NC3=CC=CC=C3N2)OC)C)OC", desc: "Proton pump inhibitor for acid reflux" },
  { name: "Simvastatin", smiles: "CCC(C)(C)C(=O)O[C@H]1C[C@H](O)CC[C@@H]2OC(=O)C[C@@H](O)CC2=C2C=C[C@H](C)C2=C1C", desc: "Statin to lower lipid levels" },
  { name: "Losartan", smiles: "CCCCCC1=NC(Cl)=C(CO)N1CC1=CC=C(C=C1)C1=CC=CC=C1C1=NNN=N1", desc: "Angiotensin II receptor antagonist" },
  { name: "Metoprolol", smiles: "CC(C)NCC(O)COC1=CC=C(CCOC)C=C1", desc: "Beta-blocker for hypertension" },
  { name: "Levothyroxine", smiles: "N[C@@H](CC1=CC(I)=C(OC2=CC(I)=C(O)C(I)=C2)C(I)=C1)C(O)=O", desc: "Thyroid hormone replacement" },
  { name: "Gabapentin", smiles: "NCCC1(CC(=O)O)CCCCC1", desc: "Medication for nerve pain & seizures" },
  { name: "Amlodipine", smiles: "CCOC(=O)C1=C(COCCN)NC(C)=C(C1C1=CC=CC=C1Cl)C(=O)OC", desc: "Calcium channel blocker for blood pressure" },
  { name: "Hydrochlorothiazide", smiles: "NS(=O)(=O)C1=CC2=C(NCNS2(=O)=O)C=C1Cl", desc: "Diuretic (water pill)" },
  { name: "Sildenafil (Viagra)", smiles: "CCCC1=NC(=C2C(=O)NC(=NC12)C1=C(OCC)C=CC(=C1)S(=O)(=O)N1CCN(C)CC1)C", desc: "Phosphodiesterase inhibitor" },
  { name: "Clopidogrel (Plavix)", smiles: "COC(=O)[C@H](C1=CC=CC=C1Cl)N2CCC3=C(C2)C=CS3", desc: "Antiplatelet medication" },
  { name: "Propranolol", smiles: "CC(C)NCC(O)COC1=CC=CC2=C1C=CC=C2", desc: "Beta-blocker for heart rate control" },
  { name: "Amoxicillin", smiles: "CC1(C(N2C(S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CC=C(O)C=C3)N)C(=O)O)C", desc: "Broad-spectrum penicillin antibiotic" },
  { name: "Ciprofloxacin", smiles: "OC(=O)C1=CN(C2CC2)C2=C(N3CCNCC3)C(F)=CC(=C2C1=O)", desc: "Fluoroquinolone antibiotic" },
  { name: "Fluoxetine (Prozac)", smiles: "CNCCC(OC1=CC=C(C=C1)C(F)(F)F)C1=CC=CC=C1", desc: "Selective serotonin reuptake inhibitor (SSRI)" },
  { name: "Prednisone", smiles: "CC12CCC3C(C1CC[C@]2(C(=O)CO)O)CCC4=CC(=O)C=C[C@]34C", desc: "Corticosteroid anti-inflammatory" },
  { name: "Furosemide (Lasix)", smiles: "NS(=O)(=O)C1=C(Cl)C=C(CC2=CC=CO2)C(C(O)=O)=C1", desc: "Loop diuretic" },
  { name: "Cetirizine (Zyrtec)", smiles: "OC(=O)COCCN1CCN(C(C1)C1=CC=C(Cl)C=C1)C1=CC=CC=C1", desc: "Antihistamine for allergies" },
  { name: "Metoclopramide", smiles: "CCN(CC)CCNC(=O)C1=C(OC)C=C(N)C(Cl)=C1", desc: "Dopamine antagonist for nausea" },
  { name: "Nifedipine", smiles: "COC(=O)C1=C(C)NC(C)=C(C1C1=CC(=CC=C1)[N+]([O-])=O)C(=O)OC", desc: "Calcium channel blocker" }
];
